/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvisorStats {
  'totalAUM' : number,
  'totalClients' : bigint,
  'avgCorpusTarget' : number,
}
export interface Client {
  'id' : bigint,
  'age' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'retirementAge' : bigint,
  'targetCorpus' : number,
  'goals' : string,
  'riskProfile' : string,
  'currentSavings' : number,
  'currentAge' : bigint,
  'monthlyExpenses' : number,
  'monthlyIncome' : number,
}
export interface SIPResult {
  'feasibilityScore' : number,
  'sipGap' : number,
  'requiredMonthlySIP' : number,
}
export interface SimulationResult {
  'percentile10' : Array<number>,
  'percentile50' : Array<number>,
  'percentile90' : Array<number>,
  'successProbability' : number,
}
export interface StressTestResult {
  'impactPercentage' : number,
  'scenario' : string,
  'adjustedSIP' : number,
  'adjustedCorpus' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<
    [
      string,
      bigint,
      string,
      number,
      number,
      number,
      number,
      bigint,
      bigint,
      string,
    ],
    bigint
  >,
  'applyStressTest' : ActorMethod<[bigint, string], [] | [StressTestResult]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateSIP' : ActorMethod<
    [number, number, bigint, number, number],
    SIPResult
  >,
  'deleteClient' : ActorMethod<[bigint], boolean>,
  'getAdvisorStats' : ActorMethod<[], AdvisorStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], [] | [Client]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'runMonteCarloSimulation' : ActorMethod<
    [number, number, bigint, number, number, bigint],
    SimulationResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      number,
      number,
      number,
      number,
      bigint,
      bigint,
      string,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];