/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StressTestResult = IDL.Record({
  'impactPercentage' : IDL.Float64,
  'scenario' : IDL.Text,
  'adjustedSIP' : IDL.Float64,
  'adjustedCorpus' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SIPResult = IDL.Record({
  'feasibilityScore' : IDL.Float64,
  'sipGap' : IDL.Float64,
  'requiredMonthlySIP' : IDL.Float64,
});
export const AdvisorStats = IDL.Record({
  'totalAUM' : IDL.Float64,
  'totalClients' : IDL.Nat,
  'avgCorpusTarget' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'retirementAge' : IDL.Nat,
  'targetCorpus' : IDL.Float64,
  'goals' : IDL.Text,
  'riskProfile' : IDL.Text,
  'currentSavings' : IDL.Float64,
  'currentAge' : IDL.Nat,
  'monthlyExpenses' : IDL.Float64,
  'monthlyIncome' : IDL.Float64,
});
export const SimulationResult = IDL.Record({
  'percentile10' : IDL.Vec(IDL.Float64),
  'percentile50' : IDL.Vec(IDL.Float64),
  'percentile90' : IDL.Vec(IDL.Float64),
  'successProbability' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'applyStressTest' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(StressTestResult)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateSIP' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64],
      [SIPResult],
      ['query'],
    ),
  'deleteClient' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdvisorStats' : IDL.Func([], [AdvisorStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'runMonteCarloSimulation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Nat],
      [SimulationResult],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StressTestResult = IDL.Record({
    'impactPercentage' : IDL.Float64,
    'scenario' : IDL.Text,
    'adjustedSIP' : IDL.Float64,
    'adjustedCorpus' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SIPResult = IDL.Record({
    'feasibilityScore' : IDL.Float64,
    'sipGap' : IDL.Float64,
    'requiredMonthlySIP' : IDL.Float64,
  });
  const AdvisorStats = IDL.Record({
    'totalAUM' : IDL.Float64,
    'totalClients' : IDL.Nat,
    'avgCorpusTarget' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'retirementAge' : IDL.Nat,
    'targetCorpus' : IDL.Float64,
    'goals' : IDL.Text,
    'riskProfile' : IDL.Text,
    'currentSavings' : IDL.Float64,
    'currentAge' : IDL.Nat,
    'monthlyExpenses' : IDL.Float64,
    'monthlyIncome' : IDL.Float64,
  });
  const SimulationResult = IDL.Record({
    'percentile10' : IDL.Vec(IDL.Float64),
    'percentile50' : IDL.Vec(IDL.Float64),
    'percentile90' : IDL.Vec(IDL.Float64),
    'successProbability' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'applyStressTest' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(StressTestResult)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateSIP' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64],
        [SIPResult],
        ['query'],
      ),
    'deleteClient' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdvisorStats' : IDL.Func([], [AdvisorStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'runMonteCarloSimulation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Nat],
        [SimulationResult],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };